### ISSUE TITLE
Chats doesn't work. 

### ISSUE THREAD

**Issue by thedirptastic** [ViribusOwner/Viribus#1]
I tried using the chat feature and it did nothing. There was an n next to the chats but it still didn't work

**Comment by ViribusOwner** [comment]
Can i ask what game you are playing? i am reworking it tonight should have an update since i realised last night that some games made there own messaging system

**Comment by ViribusOwner** [comment]
Thank you for letting me know about this issue

**Comment by thedirptastic** [comment]
Murder Mystery 2

**Comment by ViribusOwner** [comment]
ill post an update tonight fixing all chat problems
